name: Offchain Release
"on":
  push:
    branches:
      - release
jobs:
  offchain-release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - name: Semantic Release
        working-directory: offchain/github
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
